#!bin/bash

# This is a sample project/challenge to display some of the system Information
welcome="Hi "$USER
currentdirectory="You are currently in "$PWD
machinetype="You are working on "$MACHTYPE" machine"
hostname="Your hostname is "$HOSTNAME
currentdate="Logged in on "$(date +"%d-%m-%y")" at "$(date +"%h:%m:%y")
bashversion="The current bash version you are using is "$BASH_VERSION
filedate=$(date +"%d-%m-%y")
logfile="$filedate"_report.log

echo $welcome
echo $currentdirectory
echo $machinetype
echo $bashversion 
echo $hostname
echo $currentdate

cat <<- EOF > $logfile
	This report was automatically generated by my Bash Script.
	So as far I understand this file will be reading its output till it encounters the EOF
EOF
